<?php
// Generated by PBRecipe — do not edit manually.

// ── Database ─────────────────────────────────────────────────────────────────
// DB_TYPE: 'mysql' (MariaDB/MySQL), 'pgsql' (PostgreSQL), or 'sqlite'
define('DB_TYPE', '$DB_TYPE');
define('DB_HOST', '$DB_HOST');
define('DB_PORT', $DB_PORT);
define('DB_NAME', '$DB_NAME');
define('DB_USER', '$DB_USER');
define('DB_PASS', '$DB_PASS');
define('DB_PATH', '$DB_PATH');  // SQLite only: path to the .db file

// ── Recipe-type-specific strings ─────────────────────────────────────────────
$STRINGS = [
$STRINGS_PHP
];

define('SITE_TITLE', '$SITE_TITLE');
define('SITE_TYPE',  '$SITE_TYPE');
